role(a). 
role(b). 
c(1). 
c(2). 
c(3). 
base(d(A,B,e)):-c(A),c(B). 
base(d(A,B,f)):-c(A),c(B). 
base(d(A,B,g)):-c(A),c(B). 
base(h(C)):-role(C). 
input(C,i(A,B)):-c(A),c(B),role(C). 
input(C,j):-role(C). 
init(d(1,1,e)). 
init(d(1,2,e)). 
init(d(1,3,e)). 
init(d(2,1,e)). 
init(d(2,2,e)). 
init(d(2,3,e)). 
init(d(3,1,e)). 
init(d(3,2,e)). 
init(d(3,3,e)). 
init(h(a)). 
next(d(D,E,f)):-does(a,i(D,E)),true(d(D,E,e)). 
next(d(D,E,g)):-does(b,i(D,E)),true(d(D,E,e)). 
next(d(D,E,F)):-true(d(D,E,F)),distinct(F,e). 
next(d(D,E,e)):-does(F,i(G,H)),true(d(D,E,e)),or(distinct(D,G),distinct(E,H)). 
next(h(a)):-true(h(b)). 
next(h(b)):-true(h(a)). 
k(D,A):-true(d(D,1,A)),true(d(D,2,A)),true(d(D,3,A)). 
l(E,A):-true(d(1,E,A)),true(d(2,E,A)),true(d(3,E,A)). 
m(A):-true(d(1,1,A)),true(d(2,2,A)),true(d(3,3,A)). 
m(A):-true(d(1,3,A)),true(d(2,2,A)),true(d(3,1,A)). 
n(A):-k(D,A). 
n(A):-l(D,A). 
n(A):-m(A). 
o:-true(d(D,E,e)). 
legal(F,i(A,B)):-true(d(A,B,e)),true(h(F)). 
legal(a,j):-true(h(b)). 
legal(b,j):-true(h(a)). 
goal(a,100):-n(f). 
goal(a,50):-not(n(f)),not(n(g)),not(o). 
goal(a,0):-n(g). 
goal(b,100):-n(g). 
goal(b,50):-not(n(f)),not(n(g)),not(o). 
goal(b,0):-n(f). 
terminal:-n(f). 
terminal:-n(g). 
terminal:-not(o).