rem set JAVA_BIN="C:\Documents and Settings\mc\My Documents\XSBInc\XSBROOT\XSBENV\j2sdk1.4.2\bin"
rem set JAVA_BIN="C:\Program Files\Java\jdk1.5.0_09\bin"
set JAVA_BIN="C:\jdk1.6.0_17\bin"

rem OK: set XSB_BIN_DIRECTORY="C:\Documents and Settings\mc\My Documents\XSBInc\XSBROOT\XSBENV\XSB271\config\x86-pc-windows\bin"
rem OK: set XSB_BIN_DIRECTORY="C:\Documents and Settings\mc\My Documents\XSBInc\XSBROOT\XSBENV\XSB301\config\x86-pc-windows\bin"
rem XSB_BIN_DIRECTORY="C:\XSB-32\config\i686-pc-cygwin\bin"
rem XSB_BIN_DIRECTORY="C:\Xsb-3-2-7-Windows-Compiled\config\x86-pc-windows\bin"
set XSB_BIN_DIRECTORY="C:\XSB331\config\x86-pc-windows\bin"
set SWI_BIN_DIRECTORY="c:\pl\bin"
set YAP_BIN_DIRECTORY="C:\Program Files\Yap\bin"