role(a). 
init(b(1,c)). 
init(b(2,c)). 
init(b(3,c)). 
init(b(4,c)). 
init(b(5,c)). 
init(b(6,c)). 
init(b(7,c)). 
init(b(8,c)). 
init(d(1)). 
legal(a,f(A,B)):-true(b(A,c)),true(b(B,c)),g(A,B). 
legal(a,f(A,B)):-true(b(A,c)),true(b(B,c)),g(B,A). 
next(d(B)):-true(d(A)),h(A,B). 
next(b(A,i)):-does(a,f(A,B)). 
next(b(B,j)):-does(a,f(A,B)). 
next(b(A,C)):-true(b(A,C)),does(a,f(B,D)),distinct(A,B),distinct(A,D). 
terminal:-not(k). 
k:-legal(a,f(A,B)). 
goal(a,100):-true(d(5)). 
goal(a,0):-true(b(A,c)). 
l(A,B):-h(A,B). 
l(A,B):-h(A,D),true(b(D,i)),l(D,B). 
m(A,B):-h(A,D),true(b(D,c)),l(D,B). 
m(A,B):-h(A,D),true(b(D,i)),m(D,B). 
g(A,B):-h(A,D),true(b(D,j)),l(D,B). 
g(A,B):-h(A,D),true(b(D,c)),m(D,B). 
g(A,B):-h(A,D),true(b(D,i)),g(D,B). 
h(1,2). 
h(2,3). 
h(3,4). 
h(4,5). 
h(5,6). 
h(6,7). 
h(7,8). 
